# Generated by Django 5.0.1 on 2024-01-07 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('price', models.IntegerField()),
                ('special_price', models.IntegerField(blank=True, null=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('promotion_end_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_relative_url', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
