# Generated by Django 5.0.1 on 2024-01-07 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='type',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
