# Generated by Django 5.0.1 on 2024-01-07 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_food_type_alter_food_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='type',
            new_name='category',
        ),
    ]
