# Generated by Django 5.0.1 on 2024-01-08 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0005_alter_cart_food_alter_cart_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ['-created_at']},
        ),
    ]
